### ISSUE TITLE
Documentation error in ImageLoaderAdapter

### ISSUE THREAD

**Issue by muxe** [mitmel/Android-Image-Cache#8]
Hey,

great project. I just think I found a minor documentation error, which took me some to figure out.
In
https://github.com/mitmel/Android-Image-Cache/blob/master/src/edu/mit/mobile/android/imagecache/ImageLoaderAdapter.java#L43
it should say "ImageView#getTag(R.id.ic__uri)" instead of "ImageView#getTag(R.id.ic__load_id)"

**Comment by xxv** [comment]
@muxe Thanks for your report!
